name: CI

on: 
  push:
    branches:
      - feature/*

jobs:
  
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: dtpnk/docker-vdi/docker-vdi
        # image_tag: vdi_base
        registry: docker.pkg.github.com
        # build_extra_args: "--target vdi_base"

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: docker-base
  #   steps:

  #   - name: Docker login
  #     run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
  #     env:
  #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #   - name: Pull Docker image
  #     run: 
  #       docker pull docker.pkg.github.com/dtpnk/docker-vdi/docker-vdi:vdi_base

  #   - name: Build docker image (free)
      
  #     env:
  #       SHA8: ${GITHUB_SHA::8}
  #       GITHUB_REPOSITORY: ${{ github.repository }}
  #     uses: elgohr/Publish-Docker-Github-Action@master
  #     with:
  #       # <USER>/<REPO>/<DOCKER-IMAGE>
  #       name: dtpnk/docker-vdi/docker-vdi
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
  #       registry: docker.pkg.github.com
  #       buildargs: --target free
  #       tags: "dev-free"

  #   - name: Build docker image (enterprise)
  #     env:
  #       SHA8: ${GITHUB_SHA::8}
  #       GITHUB_REPOSITORY: ${{ github.repository }}
  #     uses: elgohr/Publish-Docker-Github-Action@master
  #     with:
  #       # <USER>/<REPO>/<DOCKER-IMAGE>
  #       name: dtpnk/docker-vdi/docker-vdi
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
  #       registry: docker.pkg.github.com
  #       buildargs: --target enterprise
  #       tags: "dev-enterprise"

  #   - name: Build docker image (enterprise-alt)
  #     env:
  #       SHA8: ${GITHUB_SHA::8}
  #       GITHUB_REPOSITORY: ${{ github.repository }}
  #     uses: elgohr/Publish-Docker-Github-Action@master
  #     with:
  #       # <USER>/<REPO>/<DOCKER-IMAGE>
  #       name: dtpnk/docker-vdi/docker-vdi
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
  #       registry: docker.pkg.github.com
  #       buildargs: --target enterprise_alt
  #       tags: "dev-enterprise-alt"